module.exports = {
    testEnvironment: "node",
    testMatch: ["**/src/__tests__/**/*.test.js"],
    collectCoverage: true,
    coverageDirectory: "coverage",
    moduleDirectories: ["node_modules", "src"],
    setupFiles: ["<rootDir>/src/__tests__/utils/setup.js"],
    coveragePathIgnorePatterns: ["/node_modules/",
        "src/models/",
        "src/routes/",
        "src/utils/",
        "src/config/",
        "src/validators/",
        "src/swagger/",
    "src/middleware/"],
};
